server:
    port: 8081
    servlet:
        context-path: /api/customers

customer:
  config:
    internal:
      vendor-service-endpoint: vendor-microservice

spring:
  cloud:
    stream:
      bindings:
        createVendorRecord-in-0:
          destination: vendor-queue
          group: processor
  datasource:
      password: adming@123
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
  jpa:
      hibernate:
          ddl-auto: update
      properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
